// Crop Database
const cropDatabase = [
    {
        name: 'Tomato',
        description: 'A popular garden vegetable with juicy red fruits.',
        growingTips: 'Grow in full sun and well-draining soil. Provide support for vines and regular watering.',
        soilTypes: ['Loamy', 'Sandy'],
        phRange: { min: 6.0, max: 6.8 },
        waterNeeds: ['Moderate'],
        rainfall: ['Low', 'Medium'],
        temperature: ['Moderate', 'Hot'],
        category: 'Food'
    },
    {
        name: 'Corn',
        description: 'A staple grain crop with tall stalks and ears of kernels.',
        growingTips: 'Plant in blocks rather than rows for better pollination. Requires consistent moisture during tasseling.',
        soilTypes: ['Loamy', 'Sandy'],
        phRange: { min: 5.8, max: 7.0 },
        waterNeeds: ['Moderate', 'High'],
        rainfall: ['Medium', 'High'],
        temperature: ['Moderate', 'Hot'],
        category: 'Food'
    },
    {
        name: 'Lettuce',
        description: 'A leafy green vegetable that grows quickly in cool weather.',
        growingTips: 'Grow in partial shade during hot weather. Harvest outer leaves for continuous production.',
        soilTypes: ['Loamy', 'Sandy'],
        phRange: { min: 6.0, max: 7.0 },
        waterNeeds: ['Moderate'],
        rainfall: ['Medium'],
        temperature: ['Cool', 'Moderate'],
        category: 'Food'
    },
    {
        name: 'Carrot',
        description: 'A root vegetable with orange, crisp flesh.',
        growingTips: 'Grow in loose, stone-free soil for straight roots. Thin seedlings to prevent crowding.',
        soilTypes: ['Sandy', 'Loamy'],
        phRange: { min: 6.0, max: 7.0 },
        waterNeeds: ['Moderate'],
        rainfall: ['Medium'],
        temperature: ['Cool', 'Moderate'],
        category: 'Food'
    },
    {
        name: 'Potato',
        description: 'A starchy tuber that grows underground.',
        growingTips: 'Plant seed potatoes in trenches and hill soil around plants as they grow.',
        soilTypes: ['Loamy', 'Sandy'],
        phRange: { min: 5.0, max: 6.5 },
        waterNeeds: ['Moderate'],
        rainfall: ['Medium'],
        temperature: ['Cool', 'Moderate'],
        category: 'Food'
    },
    {
        name: 'Apple Tree',
        description: 'A deciduous fruit tree that produces crisp, sweet apples.',
        growingTips: 'Requires winter chill hours. Prune annually for better fruit production.',
        soilTypes: ['Loamy', 'Clay'],
        phRange: { min: 6.0, max: 7.0 },
        waterNeeds: ['Moderate'],
        rainfall: ['Medium'],
        temperature: ['Cool', 'Moderate'],
        category: 'Fruit'
    },
    {
        name: 'Orange Tree',
        description: 'A citrus tree that produces sweet, juicy oranges.',
        growingTips: 'Protect from frost. Requires good drainage and regular feeding.',
        soilTypes: ['Loamy', 'Sandy'],
        phRange: { min: 6.0, max: 7.5 },
        waterNeeds: ['Moderate'],
        rainfall: ['Medium'],
        temperature: ['Moderate', 'Hot'],
        category: 'Fruit'
    },
    {
        name: 'Blueberry Bush',
        description: 'A shrub that produces small, sweet berries.',
        growingTips: 'Requires acidic soil. Mulch with pine needles or acidic compost.',
        soilTypes: ['Sandy', 'Peaty'],
        phRange: { min: 4.0, max: 5.5 },
        waterNeeds: ['Moderate', 'High'],
        rainfall: ['Medium', 'High'],
        temperature: ['Cool', 'Moderate'],
        category: 'Fruit'
    },
    {
        name: 'Strawberry',
        description: 'A low-growing perennial that produces sweet red berries.',
        growingTips: 'Grow in full sun. Replace plants every 3-4 years for best production.',
        soilTypes: ['Sandy', 'Loamy'],
        phRange: { min: 5.5, max: 6.5 },
        waterNeeds: ['Moderate'],
        rainfall: ['Medium'],
        temperature: ['Cool', 'Moderate'],
        category: 'Fruit'
    },
    {
        name: 'Cotton',
        description: 'A fiber crop with fluffy white bolls.',
        growingTips: 'Requires long, hot growing season. Harvest when bolls open.',
        soilTypes: ['Loamy', 'Clay'],
        phRange: { min: 5.8, max: 7.0 },
        waterNeeds: ['Moderate'],
        rainfall: ['Medium'],
        temperature: ['Hot'],
        category: 'Commercial'
    },
    {
        name: 'Wheat',
        description: 'A cereal grain used for flour and animal feed.',
        growingTips: 'Plant in fall for winter wheat or spring for spring wheat. Harvest when golden.',
        soilTypes: ['Loamy', 'Clay'],
        phRange: { min: 6.0, max: 7.5 },
        waterNeeds: ['Low', 'Moderate'],
        rainfall: ['Low', 'Medium'],
        temperature: ['Cool', 'Moderate'],
        category: 'Commercial'
    },
    {
        name: 'Soybean',
        description: 'A legume crop used for oil, protein, and soil improvement.',
        growingTips: 'Plant after last frost. Inoculate seeds with rhizobium bacteria for nitrogen fixation.',
        soilTypes: ['Loamy', 'Clay'],
        phRange: { min: 6.0, max: 7.0 },
        waterNeeds: ['Moderate'],
        rainfall: ['Medium', 'High'],
        temperature: ['Moderate', 'Hot'],
        category: 'Commercial'
    },
    {
        name: 'Coffee',
        description: 'A tropical shrub that produces coffee beans.',
        growingTips: 'Grow in partial shade. Requires high humidity and protection from frost.',
        soilTypes: ['Loamy', 'Sandy'],
        phRange: { min: 6.0, max: 6.5 },
        waterNeeds: ['Moderate', 'High'],
        rainfall: ['Medium', 'High'],
        temperature: ['Moderate', 'Hot'],
        category: 'Commercial'
    },
    {
        name: 'Oak Tree',
        description: 'A long-lived hardwood tree with acorns.',
        growingTips: 'Plant acorns in fall. Protect young trees from wildlife.',
        soilTypes: ['Loamy', 'Clay', 'Sandy'],
        phRange: { min: 4.5, max: 7.0 },
        waterNeeds: ['Low', 'Moderate'],
        rainfall: ['Medium'],
        temperature: ['Cool', 'Moderate', 'Hot'],
        category: 'Reforestation'
    },
    {
        name: 'Pine Tree',
        description: 'An evergreen conifer with needle-like leaves.',
        growingTips: 'Plant in full sun. Tolerates poor soil conditions.',
        soilTypes: ['Sandy', 'Loamy', 'Clay'],
        phRange: { min: 4.5, max: 6.5 },
        waterNeeds: ['Low', 'Moderate'],
        rainfall: ['Low', 'Medium'],
        temperature: ['Cool', 'Moderate'],
        category: 'Reforestation'
    },
    {
        name: 'Maple Tree',
        description: 'A deciduous tree with distinctive lobed leaves.',
        growingTips: 'Plant in spring or fall. Water deeply during establishment.',
        soilTypes: ['Loamy', 'Clay'],
        phRange: { min: 5.5, max: 7.3 },
        waterNeeds: ['Moderate'],
        rainfall: ['Medium', 'High'],
        temperature: ['Cool', 'Moderate'],
        category: 'Reforestation'
    },
    {
        name: 'Bamboo',
        description: 'A fast-growing grass that can form dense stands.',
        growingTips: 'Consider containment strategies as many species spread aggressively.',
        soilTypes: ['Loamy', 'Sandy'],
        phRange: { min: 5.5, max: 6.5 },
        waterNeeds: ['Moderate', 'High'],
        rainfall: ['Medium', 'High'],
        temperature: ['Moderate', 'Hot'],
        category: 'Reforestation'
    },
    {
        name: 'Rose',
        description: 'A flowering shrub with fragrant blooms.',
        growingTips: 'Plant in full sun. Prune in early spring for better flowering.',
        soilTypes: ['Loamy', 'Clay'],
        phRange: { min: 6.0, max: 7.0 },
        waterNeeds: ['Moderate'],
        rainfall: ['Medium'],
        temperature: ['Cool', 'Moderate', 'Hot'],
        category: 'Ornamental'
    },
    {
        name: 'Lavender',
        description: 'A fragrant herb with purple flowers.',
        growingTips: 'Plant in full sun. Requires excellent drainage and low humidity.',
        soilTypes: ['Sandy', 'Loamy'],
        phRange: { min: 6.5, max: 7.5 },
        waterNeeds: ['Low'],
        rainfall: ['Low'],
        temperature: ['Moderate', 'Hot'],
        category: 'Ornamental'
    },
    {
        name: 'Tulip',
        description: 'A spring-flowering bulb with cup-shaped flowers.',
        growingTips: 'Plant bulbs in fall. Provide winter chill for best flowering.',
        soilTypes: ['Sandy', 'Loamy'],
        phRange: { min: 6.0, max: 7.0 },
        waterNeeds: ['Moderate'],
        rainfall: ['Medium'],
        temperature: ['Cool', 'Moderate'],
        category: 'Ornamental'
    },
    {
        name: 'Hydrangea',
        description: 'A flowering shrub with large, showy blooms.',
        growingTips: 'Flower color changes based on soil pH. Prune after flowering.',
        soilTypes: ['Loamy', 'Sandy'],
        phRange: { min: 5.5, max: 6.5 },
        waterNeeds: ['Moderate', 'High'],
        rainfall: ['Medium', 'High'],
        temperature: ['Cool', 'Moderate'],
        category: 'Ornamental'
    },
    {
        name: 'Rice',
        description: 'A staple grain crop grown in flooded fields.',
        growingTips: 'Requires standing water during most of the growing season.',
        soilTypes: ['Clay', 'Loamy'],
        phRange: { min: 5.5, max: 6.5 },
        waterNeeds: ['High'],
        rainfall: ['High'],
        temperature: ['Moderate', 'Hot'],
        category: 'Food'
    },
    {
        name: 'Avocado Tree',
        description: 'A tropical tree that produces buttery, nutritious fruits.',
        growingTips: 'Sensitive to frost. Requires excellent drainage.',
        soilTypes: ['Loamy', 'Sandy'],
        phRange: { min: 6.0, max: 7.0 },
        waterNeeds: ['Moderate'],
        rainfall: ['Medium'],
        temperature: ['Moderate', 'Hot'],
        category: 'Fruit'
    },
    {
        name: 'Alfalfa',
        description: 'A perennial legume used for livestock feed and soil improvement.',
        growingTips: 'Deep-rooted crop that improves soil structure. Cut several times per season.',
        soilTypes: ['Loamy', 'Clay'],
        phRange: { min: 6.5, max: 7.5 },
        waterNeeds: ['Moderate'],
        rainfall: ['Medium'],
        temperature: ['Cool', 'Moderate', 'Hot'],
        category: 'Commercial'
    },
    {
        name: 'Eucalyptus',
        description: 'A fast-growing tree with aromatic leaves.',
        growingTips: 'Drought-tolerant once established. Can become invasive in some areas.',
        soilTypes: ['Sandy', 'Loamy', 'Clay'],
        phRange: { min: 5.5, max: 7.5 },
        waterNeeds: ['Low', 'Moderate'],
        rainfall: ['Low', 'Medium'],
        temperature: ['Moderate', 'Hot'],
        category: 'Reforestation'
    },
    {
        name: 'Sunflower',
        description: 'An annual with large, bright yellow flowers and edible seeds.',
        growingTips: 'Plant in full sun after last frost. Heads follow the sun until flowering.',
        soilTypes: ['Loamy', 'Sandy', 'Clay'],
        phRange: { min: 6.0, max: 7.5 },
        waterNeeds: ['Low', 'Moderate'],
        rainfall: ['Low', 'Medium'],
        temperature: ['Moderate', 'Hot'],
        category: 'Ornamental'
    }
];